- name: Configure Webserver
  hosts: webservers
  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.package:
        name: apache2
        state: present
    
    - name: Create logs directory
      ansible.builtin.file:
        path: /var/log/apache2
        state: directory
    
    - name: Start and enable Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
