- name: Basic Setup
  hosts: all
  tasks:
  - name: Create a directory
    ansible.builtin.file:
      path: /tmp/example
      state: directory
  - name: Copy a file
    ansible.builtin.copy:
      src: example.txt
      dest: /tmp/example/example.txt
  - name: Ensure Apache is running
    ansible.builtin.service:
      name: apache2
      state: started